[package]
name = "wheat"
version = "0.1.0"
authors = ["Diptodip Deb <dd@d2d.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
rayon = "1.5"
